Cleaned subsystem code from demo 2
COS301-SE-2021/GeoCode pull request #208
Opened 2021-07-05 15:07 UTC by Michael-Stroh

Cleaned up the code for the different subsystems to make the system more secure and efficent

2021-07-05 15:18 UTC, robotic-coder requested changes
getCurrentCollectable is no longer in the User controller, so frontend is unable to call it

2021-07-05 15:28 UTC, NitronBiohazard reviewed
The 6 bugs found by SonarCloud were all for if statements always evaluating to false. Investigating each if statement showed they were false positives as in all 6 instances it was possible for the statement to evaluate to true.  They have been marked as such on SonarCloud and no changes need to be made to fix them.

2021-07-05 15:29 UTC, CalebJohnstone commented
> getCurrentCollectable is no longer in the User controller, so frontend is unable to call it

Going to add the Swagger generated code in UserAPi.java back in the dev/Configuration branch so it can be pulled in from there.

2021-07-05 17:52 UTC, robotic-coder approved these changes

2021-07-06 09:20 UTC, NitronBiohazard approved these changes

2021-07-06 09:24 UTC, merged